import { useState } from 'react';
import { useApp } from '../state/AppStateProvider';
import { useToast } from '../state/ToastProvider';
import { KeyRound, ShieldCheck, ArrowUpRight, CheckCircle2, Circle, LockKeyhole, Gift } from 'lucide-react';
import { Card, Page } from '../components/common';
import { POLYMARKET_REFERRAL_CODE, POLYMARKET_REFERRAL_URL } from '../utils/links';
export function ApiKeysPage() {
 const {backend,refresh}=useApp(); const toast=useToast();
 const [keyId,setKeyId]=useState(''); const [secretKey,setSecretKey]=useState(''); const [busy,setBusy]=useState(false);
 const update=async()=>{await refresh.credentials();await refresh.backend();await refresh.account();};
 const test=async()=>{const r=await window.rom.credentials.test('mainnet'); if(!r.ok) throw new Error(r.message || 'Connection failed'); toast.success(`Connected to Polymarket US · buying power $${(r.data?.balanceUsd ?? 0).toFixed(2)}`);};
 const run=async(fn:()=>Promise<void>)=>{setBusy(true);try{await fn();}catch(e){toast.error(e instanceof Error ? e.message : 'Request failed');}finally{try{await update();}catch(e){toast.error('Could not refresh connection status');}finally{setBusy(false);}}};
 return <Page title="Polymarket US API" subtitle="One connection. Your entire trading workspace.">
 <div className="mb-6 flex items-center justify-between gap-4 rounded-xl border border-rom-border bg-rom-surface p-5">
   <div className="flex items-center gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-blue-500/10 text-blue-300"><KeyRound className="h-6 w-6" /></div><div><h3 className="font-semibold">Polymarket US</h3><p className="mt-1 text-xs text-rom-muted">Official exchange API connection</p></div></div>
   <span className={`flex items-center gap-2 rounded-full border px-3 py-1.5 text-xs ${backend.authOk ? 'border-rom-win/20 bg-rom-win/10 text-rom-win' : 'border-rom-border text-rom-muted'}`}>{backend.authOk ? <CheckCircle2 className="h-3.5 w-3.5" /> : <Circle className="h-3 w-3" />}{backend.authOk ? 'Connected' : 'Not connected'}</span>
 </div>
 <div className="grid items-start gap-6 xl:grid-cols-[minmax(0,1.6fr)_minmax(260px,1fr)]">
 <Card><div className="mb-7"><h3 className="text-base font-semibold">Connect your account</h3><p className="mt-2 text-sm leading-relaxed text-rom-muted">Enter the API credentials from your Polymarket US account.</p></div>
 <form className="space-y-5" onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await window.rom.credentials.save({keyId:keyId.trim(),secretKey:secretKey.trim(),env:'mainnet'});if(!r.ok)throw new Error(r.message || 'Save failed');setSecretKey('');await test();});}}>
 <label className="block text-sm font-medium">Key ID<input className="rom-input mt-2" required autoComplete="off" value={keyId} onChange={e=>setKeyId(e.target.value)} placeholder="Enter your API Key ID" /></label>
 <label className="block text-sm font-medium">Secret Key<input className="rom-input mt-2" required type="password" autoComplete="new-password" value={secretKey} onChange={e=>setSecretKey(e.target.value)} placeholder="Enter your Secret Key" /></label>
 <div className="flex items-start gap-2 rounded-lg bg-rom-void/50 p-3 text-xs leading-relaxed text-rom-muted"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0 text-rom-purple" />Credentials are stored locally and encrypted with your Windows account.</div>
 <div className="flex flex-wrap gap-2 border-t border-rom-border pt-5"><button disabled={busy} className="rom-btn-primary" type="submit">{busy?'Connecting…':'Save and connect'}</button><button disabled={busy} className="rom-btn-default" type="button" onClick={()=>void run(test)}>Test saved credentials</button></div>
 <button disabled={busy} className="text-xs text-rom-dim hover:text-rom-loss disabled:opacity-50" type="button" onClick={()=>void run(async()=>{const r=await window.rom.credentials.clear('mainnet');if(!r.ok)throw new Error(r.message);setSecretKey('');toast.success('Credentials removed');})}>Delete credentials</button>
 </form></Card>
 <div className="space-y-5"><div className="rounded-xl border border-blue-400/20 bg-gradient-to-br from-blue-500/10 to-rom-purple/5 p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-400/10 text-blue-300"><Gift className="h-5 w-5" /></div><div><p className="text-xs font-semibold uppercase tracking-[0.14em] text-blue-300">New-user offer</p><h3 className="mt-1 font-semibold">Get $50 to trade</h3></div></div><p className="mt-3 text-xs leading-relaxed text-rom-muted">Join Polymarket US with code <span className="font-semibold text-rom-text">{POLYMARKET_REFERRAL_CODE}</span> and make a qualifying $10 deposit to unlock the current reward.</p><button className="rom-btn-primary mt-4 w-full" type="button" onClick={()=>void window.rom.app.openExternal(POLYMARKET_REFERRAL_URL)}>Claim offer<ArrowUpRight className="h-4 w-4" /></button><p className="mt-3 text-[10px] leading-relaxed text-rom-dim">Eligibility and Polymarket terms apply. Offer may change or expire. ROM may also receive a referral reward.</p></div><Card><h3 className="font-semibold">Get connected</h3><ol className="mt-5 space-y-5">{[['Verify your account','Complete account verification with Polymarket US.'],['Create API credentials','Generate a Key ID and Secret Key in the developer portal.'],['Connect and review','Save your credentials, then review your strategies and risk limits.']].map(([title,desc],i)=><li key={title} className="flex gap-3"><span className="grid h-6 w-6 shrink-0 place-items-center rounded-full border border-rom-border text-[11px] text-rom-purple">{i+1}</span><div><p className="text-sm font-medium">{title}</p><p className="mt-1 text-xs leading-relaxed text-rom-muted">{desc}</p></div></li>)}</ol><button className="rom-btn-default mt-6 w-full" onClick={()=>void window.rom.app.openExternal('https://polymarket.us/developer')}>Open developer portal<ArrowUpRight className="h-4 w-4" /></button></Card>
 <div className="flex gap-3 px-1 text-xs leading-relaxed text-rom-muted"><ShieldCheck className="h-5 w-5 shrink-0 text-rom-win" /><p>Connection tests only read your account balance. Trading is controlled separately in each engine.</p></div></div>
 </div></Page>;
}
